"""
Canonical Knowledge Base Seed Database for AI Startups and Products.
Contains 50+ premier AI entities, aliases, legal variations, and domain mappings.
"""

from typing import Dict, List, Any

CANONICAL_AI_STARTUPS: Dict[str, Dict[str, Any]] = {
    "OpenAI": {
        "canonical_name": "OpenAI",
        "domains": ["openai.com"],
        "aliases": ["Open AI", "OpenAI, Inc.", "OpenAI Inc", "OpenAI LLC", "OpenAI LP", "OpenAI Global"],
        "category": "Frontier AI & Large Language Models",
        "flagship_products": ["ChatGPT", "GPT-4o", "DALL-E", "Sora", "Whisper"],
    },
    "Anthropic": {
        "canonical_name": "Anthropic",
        "domains": ["anthropic.com"],
        "aliases": ["Anthropic PBC", "Anthropic AI", "Anthropic, PBC", "Anthropic Inc."],
        "category": "AI Safety & Large Language Models",
        "flagship_products": ["Claude", "Claude 3.5 Sonnet", "Claude 3 Opus", "Claude 3 Haiku"],
    },
    "Mistral AI": {
        "canonical_name": "Mistral AI",
        "domains": ["mistral.ai"],
        "aliases": ["Mistral", "Mistral AI SAS", "MistralAI"],
        "category": "Open Weight Frontier Models",
        "flagship_products": ["Mistral 7B", "Mixtral 8x7B", "Mistral Large", "Codestral", "Le Chat"],
    },
    "Cohere": {
        "canonical_name": "Cohere",
        "domains": ["cohere.com", "cohere.ai"],
        "aliases": ["Cohere Inc.", "Cohere AI", "Cohere Inc"],
        "category": "Enterprise AI & Embeddings",
        "flagship_products": ["Command R+", "Command R", "Cohere Embed", "Cohere Rerank"],
    },
    "Hugging Face": {
        "canonical_name": "Hugging Face",
        "domains": ["huggingface.co"],
        "aliases": ["HuggingFace", "Hugging Face, Inc.", "Hugging Face Inc", "Hugging Face Inc."],
        "category": "AI Community & Model Platform",
        "flagship_products": ["Transformers", "Hugging Face Hub", "Diffusers", "Spaces", "Gradio"],
    },
    "Perplexity AI": {
        "canonical_name": "Perplexity AI",
        "domains": ["perplexity.ai"],
        "aliases": ["Perplexity", "Perplexity, Inc.", "Perplexity Inc", "Perplexity AI Inc"],
        "category": "Conversational AI Search Engine",
        "flagship_products": ["Perplexity Pro", "Perplexity Pages", "Sonar"],
    },
    "Scale AI": {
        "canonical_name": "Scale AI",
        "domains": ["scale.com"],
        "aliases": ["Scale", "Scale AI, Inc.", "Scale AI Inc.", "Scale.com"],
        "category": "Data Infrastructure for AI",
        "flagship_products": ["Scale Donovan", "Scale GenAI Platform", "Scale Rapid"],
    },
    "Midjourney": {
        "canonical_name": "Midjourney",
        "domains": ["midjourney.com"],
        "aliases": ["Midjourney Inc.", "Midjourney Inc", "Midjourney AI"],
        "category": "Generative Image & Art AI",
        "flagship_products": ["Midjourney v6", "Midjourney Web"],
    },
    "Stability AI": {
        "canonical_name": "Stability AI",
        "domains": ["stability.ai"],
        "aliases": ["Stability", "Stability AI Ltd.", "Stability AI Ltd", "Stability.ai"],
        "category": "Generative Media & Open Foundation Models",
        "flagship_products": ["Stable Diffusion", "SDXL", "Stable Video", "Stable Audio"],
    },
    "Cursor": {
        "canonical_name": "Cursor",
        "domains": ["cursor.com", "cursor.sh"],
        "aliases": ["Anysphere", "Anysphere Inc.", "Cursor IDE", "Cursor AI"],
        "category": "AI Code Editor & Developer Tools",
        "flagship_products": ["Cursor Editor", "Cursor Tab", "Cursor Composer"],
    },
    "Runway": {
        "canonical_name": "Runway",
        "domains": ["runwayml.com"],
        "aliases": ["Runway AI", "RunwayML", "Runway AI, Inc.", "Runway Inc"],
        "category": "Generative Video & Creative AI",
        "flagship_products": ["Gen-3 Alpha", "Gen-2", "Runway Studios"],
    },
    "Pinecone": {
        "canonical_name": "Pinecone",
        "domains": ["pinecone.io"],
        "aliases": ["Pinecone Systems", "Pinecone Systems, Inc.", "Pinecone Inc"],
        "category": "Vector Database & Retrieval Infrastructure",
        "flagship_products": ["Pinecone Serverless", "Pinecone Vector DB"],
    },
    "Qdrant": {
        "canonical_name": "Qdrant",
        "domains": ["qdrant.tech", "qdrant.io"],
        "aliases": ["Qdrant Solutions", "Qdrant Solutions GmbH"],
        "category": "Vector Search Engine",
        "flagship_products": ["Qdrant Cloud", "Qdrant Hybrid Search"],
    },
    "Weaviate": {
        "canonical_name": "Weaviate",
        "domains": ["weaviate.io"],
        "aliases": ["Weaviate B.V.", "Weaviate Inc."],
        "category": "Open Source Vector Database",
        "flagship_products": ["Weaviate Cloud", "Weaviate Embeddings"],
    },
    "Chroma": {
        "canonical_name": "Chroma",
        "domains": ["trychroma.com"],
        "aliases": ["Chroma DB", "ChromaDB", "Chroma, Inc."],
        "category": "Embeddings Database for AI",
        "flagship_products": ["Chroma Serverless", "Chroma Core"],
    },
    "LangChain": {
        "canonical_name": "LangChain",
        "domains": ["langchain.com"],
        "aliases": ["LangChain Inc.", "LangChain, Inc.", "LangChain AI"],
        "category": "LLM Application Framework",
        "flagship_products": ["LangChain Core", "LangSmith", "LangGraph"],
    },
    "LlamaIndex": {
        "canonical_name": "LlamaIndex",
        "domains": ["llamaindex.ai"],
        "aliases": ["Llama Index", "LlamaIndex Inc.", "Run Llama"],
        "category": "Data Framework for LLM Applications",
        "flagship_products": ["LlamaCloud", "LlamaParse", "LlamaExtract"],
    },
    "Together AI": {
        "canonical_name": "Together AI",
        "domains": ["together.ai"],
        "aliases": ["Together", "Together Computer", "Together AI Inc."],
        "category": "Fast Cloud AI Inference & GPU Cloud",
        "flagship_products": ["Together Inference Engine", "Together Fine-tuning"],
    },
    "Groq": {
        "canonical_name": "Groq",
        "domains": ["groq.com"],
        "aliases": ["Groq Inc.", "Groq, Inc.", "GroqCloud", "Groq LPU"],
        "category": "LPU Inference Hardware & Cloud",
        "flagship_products": ["GroqCloud", "Groq LPU Engine"],
    },
    "Cerebras": {
        "canonical_name": "Cerebras",
        "domains": ["cerebras.net", "cerebras.ai"],
        "aliases": ["Cerebras Systems", "Cerebras Systems Inc.", "Cerebras AI"],
        "category": "Wafer Scale AI Chips & Inference",
        "flagship_products": ["Wafer-Scale Engine", "CS-3", "Cerebras Inference"],
    },
    "Fireworks AI": {
        "canonical_name": "Fireworks AI",
        "domains": ["fireworks.ai"],
        "aliases": ["Fireworks", "Fireworks AI Inc.", "Fireworks.ai"],
        "category": "Production AI Model Serving",
        "flagship_products": ["Fireworks GenAI Platform", "Function Calling Models"],
    },
    "Replicate": {
        "canonical_name": "Replicate",
        "domains": ["replicate.com"],
        "aliases": ["Replicate Inc.", "Replicate, Inc.", "Replicate AI"],
        "category": "Cloud Model Hosting & Inference API",
        "flagship_products": ["Replicate Predictions", "Cog"],
    },
    "Synthesia": {
        "canonical_name": "Synthesia",
        "domains": ["synthesia.io"],
        "aliases": ["Synthesia Ltd.", "Synthesia Limited", "Synthesia AI"],
        "category": "AI Video Generation & Avatars",
        "flagship_products": ["Synthesia STUDIO", "Expressive Avatars"],
    },
    "ElevenLabs": {
        "canonical_name": "ElevenLabs",
        "domains": ["elevenlabs.io"],
        "aliases": ["Eleven Labs", "ElevenLabs Inc.", "Eleven Labs Inc."],
        "category": "AI Voice Synthesis & Audio AI",
        "flagship_products": ["VoiceLab", "Dubbing Studio", "Eleven Multilingual v2", "Reader App"],
    },
    "Character.ai": {
        "canonical_name": "Character.ai",
        "domains": ["character.ai"],
        "aliases": ["Character AI", "Character Technologies", "Character Technologies Inc."],
        "category": "Conversational AI & Persona Agents",
        "flagship_products": ["Character.ai Chat", "Character Voices"],
    },
    "Inflection AI": {
        "canonical_name": "Inflection AI",
        "domains": ["inflection.ai"],
        "aliases": ["Inflection", "Inflection AI, Inc.", "Inflection AI Inc"],
        "category": "Personal AI & Foundation Models",
        "flagship_products": ["Pi", "Inflection-2.5"],
    },
    "Glean": {
        "canonical_name": "Glean",
        "domains": ["glean.com"],
        "aliases": ["Glean Technologies", "Glean Technologies, Inc."],
        "category": "Enterprise AI Search & Knowledge Graph",
        "flagship_products": ["Glean Work AI Platform", "Glean Search", "Glean Assistant"],
    },
    "Jasper": {
        "canonical_name": "Jasper",
        "domains": ["jasper.ai"],
        "aliases": ["Jasper AI", "Jasper AI, Inc.", "UseProof"],
        "category": "AI Marketing & Enterprise Copywriting",
        "flagship_products": ["Jasper App", "Jasper Brand Voice", "Jasper Studio"],
    },
    "Copy.ai": {
        "canonical_name": "Copy.ai",
        "domains": ["copy.ai"],
        "aliases": ["Copy AI", "CopyAI", "Copy.ai Inc."],
        "category": "AI Marketing & GTM Automation",
        "flagship_products": ["Copy.ai Workflows", "Chat by Copy.ai"],
    },
    "Writer": {
        "canonical_name": "Writer",
        "domains": ["writer.com"],
        "aliases": ["Writer AI", "Writer, Inc.", "Writer Inc."],
        "category": "Full-Stack Generative AI for Enterprise",
        "flagship_products": ["Writer Palmyra LLMs", "Writer Knowledge Graph", "Writer AI Studio"],
    },
    "Harvey": {
        "canonical_name": "Harvey",
        "domains": ["harvey.ai"],
        "aliases": ["Harvey AI", "Harvey Legal", "Harvey AI, Inc."],
        "category": "AI Platform for Legal & Professional Services",
        "flagship_products": ["Harvey Assistant", "Harvey Workflows"],
    },
    "Hebbia": {
        "canonical_name": "Hebbia",
        "domains": ["hebbia.ai"],
        "aliases": ["Hebbia AI", "Hebbia, Inc."],
        "category": "AI Research & Knowledge Extraction",
        "flagship_products": ["Matrix", "Hebbia Search"],
    },
    "Cognition": {
        "canonical_name": "Cognition",
        "domains": ["cognition.ai"],
        "aliases": ["Cognition AI", "Cognition Labs", "Cognition Labs Inc."],
        "category": "Autonomous AI Software Engineers",
        "flagship_products": ["Devin", "Devin AI Engineer"],
    },
    "Poolside": {
        "canonical_name": "Poolside",
        "domains": ["poolside.ai"],
        "aliases": ["Poolside AI", "Poolside AI SAS"],
        "category": "Foundation Models for Software Development",
        "flagship_products": ["Poolside Coding Assistant"],
    },
    "Magic": {
        "canonical_name": "Magic",
        "domains": ["magic.dev"],
        "aliases": ["Magic AI", "Magic.dev", "Magic Technologies Inc."],
        "category": "Ultra-Long Context Models for Software",
        "flagship_products": ["Magic LTM-2-mini", "Magic HashHop"],
    },
    "Abridge": {
        "canonical_name": "Abridge",
        "domains": ["abridge.com"],
        "aliases": ["Abridge AI", "Abridge AI Inc."],
        "category": "Generative AI for Clinical Documentation",
        "flagship_products": ["Abridge Clinical AI"],
    },
    "Hippocratic AI": {
        "canonical_name": "Hippocratic AI",
        "domains": ["hippocraticai.com"],
        "aliases": ["Hippocratic", "Hippocratic AI, Inc."],
        "category": "Safety-Focused Medical LLMs",
        "flagship_products": ["Polaris", "Hippocratic Agent"],
    },
    "Sierra": {
        "canonical_name": "Sierra",
        "domains": ["sierra.ai"],
        "aliases": ["Sierra AI", "Sierra Interactive Inc."],
        "category": "Conversational AI Agents for Enterprise",
        "flagship_products": ["Sierra Agent Platform"],
    },
    "Decagon": {
        "canonical_name": "Decagon",
        "domains": ["decagon.ai"],
        "aliases": ["Decagon AI", "Decagon Inc."],
        "category": "AI Customer Support Agents",
        "flagship_products": ["Decagon Engine"],
    },
    "Cresta": {
        "canonical_name": "Cresta",
        "domains": ["cresta.com"],
        "aliases": ["Cresta AI", "Cresta Technologies"],
        "category": "Real-time Intelligence for Contact Centers",
        "flagship_products": ["Cresta Director", "Cresta Agent Assist"],
    },
    "Pika": {
        "canonical_name": "Pika",
        "domains": ["pika.art"],
        "aliases": ["Pika Labs", "Pika Labs Inc.", "Pika AI"],
        "category": "AI Video Generation Platform",
        "flagship_products": ["Pika 1.0", "Pika 2.0", "Pikaffects"],
    },
    "Luma AI": {
        "canonical_name": "Luma AI",
        "domains": ["lumalabs.ai"],
        "aliases": ["Luma", "Luma Labs", "Luma AI Inc."],
        "category": "Neural Radiance Fields & Generative Video",
        "flagship_products": ["Dream Machine", "Luma Interactive NeRF"],
    },
    "Kling AI": {
        "canonical_name": "Kling AI",
        "domains": ["klingai.org", "klingai.com"],
        "aliases": ["Kling", "Kuaishou Kling"],
        "category": "High-Fidelity AI Video Generation",
        "flagship_products": ["Kling 1.5"],
    },
    "Vapi": {
        "canonical_name": "Vapi",
        "domains": ["vapi.ai"],
        "aliases": ["Vapi AI", "Vapi.ai Inc."],
        "category": "Voice AI Orchestration & Real-time Agents",
        "flagship_products": ["Vapi Server", "Vapi Real-time Voice API"],
    },
    "Bland AI": {
        "canonical_name": "Bland AI",
        "domains": ["bland.ai"],
        "aliases": ["Bland", "Bland.ai", "Bland AI Inc."],
        "category": "Phone Call AI Automation",
        "flagship_products": ["Bland Turbo", "Bland Voice Agent"],
    },
    "Tavus": {
        "canonical_name": "Tavus",
        "domains": ["tavus.io"],
        "aliases": ["Tavus AI", "Tavus Inc."],
        "category": "Conversational Digital Human Video",
        "flagship_products": ["Phoenix-2", "Conversational Video Interface"],
    },
    "HeyGen": {
        "canonical_name": "HeyGen",
        "domains": ["heygen.com"],
        "aliases": ["HeyGen AI", "Movio", "SurrealX"],
        "category": "AI Video Generation & Localization",
        "flagship_products": ["HeyGen Video Translate", "Interactive Avatar"],
    },
    "Captions": {
        "canonical_name": "Captions",
        "domains": ["captions.ai"],
        "aliases": ["Captions AI", "Captions.ai Inc."],
        "category": "AI Studio for Video Creators",
        "flagship_products": ["Captions App", "AI Eye Contact", "AI Lipdub"],
    },
    "Descript": {
        "canonical_name": "Descript",
        "domains": ["descript.com"],
        "aliases": ["Descript Inc.", "Descript, Inc."],
        "category": "AI Video & Audio Editor",
        "flagship_products": ["Descript Overdub", "Descript Studio Sound", "Underlord"],
    },
    "Phind": {
        "canonical_name": "Phind",
        "domains": ["phind.com"],
        "aliases": ["Phind AI", "HelloCognition", "Phind.com"],
        "category": "AI Search Engine for Developers",
        "flagship_products": ["Phind-70B", "Phind Instant"],
    },
    "You.com": {
        "canonical_name": "You.com",
        "domains": ["you.com"],
        "aliases": ["SuSea, Inc.", "You.com Inc", "You.com AI"],
        "category": "AI Search Engine & Multi-Agent Assistant",
        "flagship_products": ["YouChat", "YouPro", "Genie"],
    },
    "Kindo": {
        "canonical_name": "Kindo",
        "domains": ["kindo.ai"],
        "aliases": ["Kindo AI", "Kindo.ai"],
        "category": "Enterprise Generative AI Security & Workflow",
        "flagship_products": ["Kindo Enterprise Gateway"],
    },
}
